#!/bin/zsh

# be safe
set -eu -o pipefail

echo '################################'
echo '#### Running YADM Bootstrap ####'
echo '################################'


echo 'Make sure yadm repo is accessed by SSH'
yadm remote set-url origin "git@github.com:kgizdov/dotfiles.git"

echo 'Set sparse-checkout to drop LICENSE and README.md'
yadm gitconfig core.sparsecheckout true
echo '/*' > "${HOME}/.yadm/repo.git/info/sparse-checkout"
echo '!LICENSE' >> "${HOME}/.yadm/repo.git/info/sparse-checkout"
echo '!README.md' >> "${HOME}/.yadm/repo.git/info/sparse-checkout"
